logging:
  file: logs/production_profile_app.log
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    org.springframework.web: WARN
    guru.springframework.controllers: WARN
    org.hibernate: WARN
    
files:
    base: D:/GL ERP/Socle_appBlank/app/data
    in: ${files.base}/in
    pattern: listeUsers_*.xml
    done: done
    